### ISSUE TITLE
BUG: Error: Unable to connect

### ISSUE THREAD

**Issue by abhisingh3195** [ceramicnetwork/ceramic#57] opened 2021-06-07 09:31 UTC
**Describe the bug**
 Error: Unable to connect on ceramic popup

**To Reproduce**
1. Using package '@3id/connect'
2. Connecting with 3id with the following code
```
import { ThreeIdConnect, EthereumAuthProvider } from '@3id/connect'
const threeIdConnect = new ThreeIdConnect()
let authProvider = new EthereumAuthProvider(window.ethereum, address)
yield threeIdConnect.connect(authProvider)
const didProvider = yield threeIdConnect.getDidProvider()
const CERAMIC_URL = "https://ceramic-clay.3boxlabs.com";
const ceramic = new Ceramic(CERAMIC_URL)
yield ceramic.setDIDProvider(didProvider)
```

**Screenshots**
Pic 1 - These APIs are getting called only, after which i get the error in Pic 2
![Screenshot from 2021-06-07 11-56-45](https://user-images.githubusercontent.com/62532644/120992703-7a91c380-c7a0-11eb-9cfc-8215db366b12.png)

Pic 2
![Screenshot from 2021-06-07 11-56-53](https://user-images.githubusercontent.com/62532644/120992725-7f567780-c7a0-11eb-9d56-6e49782b37ed.png)

Pic 3 and Pic 4 - Getting error on this API only for now but still other APIs are getting called which further gives the error on popup.
![Screenshot from 2021-06-07 13-08-15](https://user-images.githubusercontent.com/62532644/120992744-83829500-c7a0-11eb-8e0a-36464702e2c5.png)
![Screenshot from 2021-06-07 13-08-27](https://user-images.githubusercontent.com/62532644/120992755-87161c00-c7a0-11eb-8ac3-e9dfab4da1e8.png)

**Ceramic versions** 
"@3id/connect": "^0.1.3",
"@ceramicnetwork/http-client": "^0.9.3",
"@ceramicstudio/idx": "^0.7.0",

**Machine, OS, browser information (please complete the following information):**
Linux,testing on Chrome and Brave only for right now.

**Comment by oed** [comment] 2021-06-07 09:51
Duplicate of https://github.com/ceramicstudio/3id-connect/issues/79 closing

**Closed by oed** 2021-06-07 09:51 UTC
Labels: bug, help wanted
