### ISSUE TITLE
BUG: 500 Request timed out

### ISSUE THREAD

**Issue by abhisingh3195** [ceramicnetwork/ceramic#55] opened 2021-05-26 06:59 UTC
**Describe the bug**
Since today only, i am getting error on api https://ceramic-clay.3boxlabs.com/api/v0/pins/k2t6wyfsu4pg1fj3y2j0zs1q9123cqxskk09n8bbs2b080t3wh73xh5xcikrla and https://ceramic-clay.3boxlabs.com/api/v0/documents/k3y52l7qbv1frxi800msx6cub6qxt6m0qgwe0jssvs1c0lhoww5kh4xh5h1jn8hds

**To Reproduce**
1. Using package '@3id/connect'
2. Connecting with 3id with the following code

    `import { ThreeIdConnect, EthereumAuthProvider } from '@3id/connect'`
    `const threeIdConnect = new ThreeIdConnect()`
    `let authProvider = new EthereumAuthProvider(window.ethereum, address)`
    `yield threeIdConnect.connect(authProvider)`
    `const didProvider = yield threeIdConnect.getDidProvider()`
    `const CERAMIC_URL = "https://ceramic-clay.3boxlabs.com";`
    `const ceramic = new Ceramic(CERAMIC_URL)`
    `yield ceramic.setDIDProvider(didProvider)`

Getting error on code statement - yield ceramic.setDIDProvider(didProvider).

**Expected behavior**
Gets connected to ceramic

**Screenshots**
![Screenshot from 2021-05-26 11-41-40](https://user-images.githubusercontent.com/62532644/119615869-8a62ec80-be1d-11eb-92a6-6e3c851559d7.png)
![Screenshot from 2021-05-26 11-35-07](https://user-images.githubusercontent.com/62532644/119615870-8c2cb000-be1d-11eb-98ae-c914dc67c17b.png)

**Ceramic versions** 
"@3id/connect": "^0.1.3",
"@ceramicnetwork/http-client": "^0.9.3",
"@ceramicstudio/idx": "^0.7.0",

**Machine, OS, browser information (please complete the following information):**
Linux,testing on Chrome and Brave only for right now.

**Additional context**
Error coming since today only,was working fine till yesterday with the same written code.

**Comment by stbrody** [comment] 2021-05-26 13:48
We are seeing this as well and are looking into it.  Will update here once we have a resolution

**Comment by abhisingh3195** [comment] 2021-05-31 06:15
Instead of that issue i am facing this now. Getting Error: unable to connect while connecting to ceramic.

![Screenshot from 2021-05-31 11-13-52](https://user-images.githubusercontent.com/62532644/120148116-59136380-c205-11eb-82ff-e8ae444eb836.png)

![Screenshot from 2021-05-31 11-13-30](https://user-images.githubusercontent.com/62532644/120148176-6d576080-c205-11eb-9da8-6985398c7254.png)

**Comment by abhisingh3195** [comment] 2021-05-31 09:02
**This is a very critical situation for us, we are already at 90% completion of our mvp. With this issue at this stage it will be very risky for us to  switch to a different application. We already have investors who like this solution so i please request to take this on priority and let us know of solution quickly. We want to push this to production soon and we are heavily relying on your solution. Please understand.**

**Comment by oed** [comment] 2021-05-31 09:08
@abhisingh3195 This issue is currently our top priority and we are working hard on fixing it!

**Comment by oed** [comment] 2021-05-31 16:43
@abhisingh3195 What's the setup you are seeing these issues with? Which node are you connecting to?

**Comment by ukstv** [comment] 2021-05-31 17:08
I guess it is the same as in https://github.com/ceramicnetwork/js-ceramic/issues/1413

**Comment by abhisingh3195** [comment] 2021-06-01 07:42
Hi, this issue is resolved today, but for your queries
@oed Setup -
Ceramic versions
"@3id/connect": "^0.1.3",
"@ceramicnetwork/http-client": "^0.9.3",
"@ceramicstudio/idx": "^0.7.0",

Machine, OS, browser information (please complete the following information):
Linux,testing on Chrome and Brave only for right now.

**Comment by abhisingh3195** [comment] 2021-06-01 07:45
@ukstv Yes i was having timeout issue last week but after that got resolved, got this new one https://github.com/ceramicnetwork/ceramic/issues/55#issuecomment-851214861 and it's also resolved today.

**Comment by oed** [comment] 2021-06-01 08:29
@abhisingh3195 So it's completely resolved for you? 

Was also wondering which Ceramic nodes you are connecting to using the http-client?

**Comment by oed** [comment] 2021-06-02 10:15
Thanks for confirming! Closing.

**Comment by abhisingh3195** [comment] 2021-06-04 05:55
@oed **Can we please reopen this issue, we are again getting these following errors.**

API - https://ceramic-private-clay.3boxlabs.com/api/v0/pins/k2t6wyfsu4pg2jshugiszyrv90fvyn3bef80qpvlebqhtotx9qiu4d0c3n1wop
Error - "Request timed out"
API - https://ceramic-private-clay.3boxlabs.com/api/v0/pins/k2t6wyfsu4pfxtkzli50amlthqtd8jbcvgqfsbq2ow71u0jfxk73pz2h3pntg2
Error - "Request timed out"
API - https://beta.3box.io/address-server/odbAddress/0x4af26cc1c9e424bad9e34db1e62ac7bb33c7dc41
Error - message: "address not linked"
           status: "error"

![Screenshot from 2021-06-04 11-16-04](https://user-images.githubusercontent.com/62532644/120752351-292acf80-c527-11eb-8ef3-88acedf4b848.png)
![Screenshot from 2021-06-04 11-16-25](https://user-images.githubusercontent.com/62532644/120752366-33e56480-c527-11eb-820c-da25c3f71d89.png)
![Screenshot from 2021-06-04 11-16-40](https://user-images.githubusercontent.com/62532644/120752421-4d86ac00-c527-11eb-8f98-e7eb19ebc913.png)

**Comment by oed** [comment] 2021-06-04 09:23
This likely happened as the Clay nodes that 3Box Labs provide. You can check https://chat.ceramic.network for status.

**Comment by abhisingh3195** [comment] 2021-06-04 10:26
@oed Thanks for the response, can you please tell me when can i expect this to be working again?

**Comment by oed** [comment] 2021-06-04 11:12
It should be working now! If it's not then something is up.
cc @v-stickykeys

**Comment by abhisingh3195** [comment] 2021-06-04 12:14
@oed It's not working actually,can you please look into it.

**Comment by stbrody** [comment] 2021-06-04 18:45
Hi @abhisingh3195, we have identified the cause of the issue and are working on a mitigation. Will post here when the mitigation is in place

**Comment by abhisingh3195** [comment] 2021-06-07 06:28
Hi @stbrody @oed 
After i got the update on discord that it's resolved but still my team is facing the issue.

Only these apis are getting hit (pic 1)
![Screenshot from 2021-06-07 11-56-45](https://user-images.githubusercontent.com/62532644/120969192-7efdb280-c787-11eb-838a-e3f543d7bce5.png)
 
![Screenshot from 2021-06-07 11-56-53](https://user-images.githubusercontent.com/62532644/120969262-93da4600-c787-11eb-9559-45bb35b4f466.png)

**Comment by abhisingh3195** [comment] 2021-06-07 07:38
Note - we did not get timeout issue on any api but last api which is getting hit is https://ceramic-private-clay.3boxlabs.com/api/v0/multiqueries , even though it's response is 200, we get the error on ceramic popup 'Error: Unable to connect'.
Only error on api which we are getting now is https://beta.3box.io/address-server/odbAddress/0x4af26cc1c9e424bad9e34db1e62ac7bb33c7dc41

![Screenshot from 2021-06-07 13-08-15](https://user-images.githubusercontent.com/62532644/120977874-77430b80-c791-11eb-9dd4-024c23494a5d.png)
![Screenshot from 2021-06-07 13-08-27](https://user-images.githubusercontent.com/62532644/120977882-7b6f2900-c791-11eb-886d-6688b575c70b.png)

**Comment by oed** [comment] 2021-06-07 09:15
@abhisingh3195 This seems like a separate issue. Would probably be better if you created an issue for that separately in the https://github.com/ceramicstudio/3id-connect repo!

Sidenote, the 404 errors from beta.3box.io are expected and you can disregard them!

Closing this issue as the 500 issue should have been resolved.

**Closed by oed** 2021-06-07 09:15 UTC
Labels: additional work, bug, p1

**Comment by abhisingh3195** [comment] 2021-06-07 09:32
Sure @oed , created a new issue here https://github.com/ceramicnetwork/ceramic/issues/57

**Comment by abhisingh3195** [comment] 2021-06-07 09:37
My bad, created an issue on this repo instead of 3id-connect, i have created a new issue https://github.com/ceramicstudio/3id-connect/issues/79
